#dependabot config for npm

version: 2
updates:
  - directory: '/'
    open-pull-requests-limit: 10
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
    groups:
      emotion:
        patterns:
          - "@emotion*"
      mui:
        patterns:
          - "@mui*"
      react-deps:
        patterns:
          - "react*"
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"